### ISSUE TITLE
Ability to hard-code an `include` query string value

### ISSUE THREAD

**Issue by chrisdpeters** [tiagopog/jsonapi-utils#36]
This is a new issue spawned from discussion in #19.

Honestly, I've just started using this gem and don't know any details about its internals. So I'm not quite sure where to start in recommending how it should work. Would it be an option passed to `jsonapi_render`?

From the spec, it seems that we should encourage only overriding the `include` value if none is already provided in the query string.

**Comment by tiagopog** [comment]
Hey, @chrisdpeters! Thanks for bringing up this discussion since [this thread](https://github.com/cerebris/jsonapi-resources/issues/389) clearly show us a lack of implementation for such feature in the JR's side.

IMHO we would go for a resource-based approach, since resources' settings are responsible to let JU and JR know what needs to be selected, included, filtered, ordered etc. With a macro like `default_include :posts` in the `UserResource` class, it would be very easy to access this value (e.g. `UserResource.default_include`) and deal with it at the controller level, in a transparent way to the end user.

Usage example:

```ruby
class UserResource < JSONAPI::Resource
  attributes :name
  has_many :posts
  default_include :posts
end
```

Thoughts?

**Comment by chrisdpeters** [comment]
@tiagopog In the case of my application, I think the knowledge of what to include exists in the controller. The pattern that I'm seeking is for certain endpoints to auto-include a related record on `create`, `update`, and `destroy`. I don't need it on `index` or `show`.

The main rationale is with drafts that are saved on those actions, and it's helpful to return that info along with the save because the clients will likely need it anyway. For example, on an `update` action, the "main" object stays the same, but the requested changes get stashed away into a related `draft`.

Does that make sense? If I'm understanding how all of this works, you couldn't do something like this:

```ruby
default_include :posts, only: [:create, :update, :destroy]
```

**Comment by chrisdpeters** [comment]
@tiagopog It looks like perhaps this pattern is going to be hard for me to work with. I'll probably need to suck it up and require that the `include` query string be provided along with the requests that I'm talking about above.

**Comment by tiagopog** [comment]
@chrisdpeters here at the company we do just like the way you mentioned previously, I mean, clients require explicitly what they want to include along with the main resource, even for POST/PUT/PATCH request. If we decide to implement a macro like that `default_include` idea, the idiom `default_include :resource, only: actions` looks good to me.

**Comment by chrisdpeters** [comment]
In terms of my interests for my current project, this feature is a very low priority. I think that providing the `include` query param along with the create/update/delete will be sufficient.

**Comment by tiagopog** [comment]
Since the macro proposed here (`default_include`) is strongly related to the JR's resource layer – and JU is focused on helpers for controllers – I think this implementation is more suitable to the JR's codebase.
