### ISSUE TITLE
Pagination for each resources

### ISSUE THREAD

**Issue by peco8** [tiagopog/jsonapi-utils#50]
First off, this gem is pretty awesome!

This is not an issue but I just wonder about the pagination.

I know we can define the default pagination, but could I set the pagination for each models/resources?
Should I use library [kaminari](https://github.com/kaminari/kaminari) or something?

**Comment by tiagopog** [comment]
Hey there, @peco8!

You mean to set the pagination's config (`default_page_size` and `maximum_page_size`) for each resource?

If so, it's not natively supported by JU nor JR (as far as I know), but there's a workaround: you can [create custom paginators](https://github.com/tiagopog/jsonapi-utils#paginators) and then encapsulate there the needed logic for each resource.

For example, say you want to create a custom paginator for `UserResource` and `PostResource`, you could do something like this:

```ruby
# app/resources/paginators/custom_paginator.rb
module Paginators
  class CustomPaginator < JSONAPI::Paginator
    def pagination_range(page_params, default_page_size:)
      offset = page_params['offset'] || 0
      limit  = page_params['limit'] || default_page_size # apply a custom default page size for each resource
      offset..offset + limit - 1 # resulting range
    end
  end
end

# app/resources/paginators/user_custom_paginator.rb
module Paginators
  class UserCustomPaginator < JSONAPI::Paginator
    def pagination_range(page_params)
      super(page_params, default_page_size: 50)
    end
  end
end

# app/resources/paginators/post_custom_paginator.rb
module Paginators
  class PostCustomPaginator < JSONAPI::Paginator
    def pagination_range(page_params)
      super(page_params, default_page_size: 10)
    end
  end
end
```

Then it's all about to set those custom paginators in their own resources:

```ruby
class UserResource < JSONAPI::Resource
  # ...
  paginator :user_custom_paginator
end

class PostResource < JSONAPI::Resource
  # ...
  paginator :post_custom_paginator
end
```

**Comment by tiagopog** [comment]
I will hopefully add this to the `README` as soon as a I get some free time :-)

**Comment by peco8** [comment]
@tiagopog 
Thanks for the quick response even you seem pretty busy busy!
I'll try that out sometime soon :)

**Comment by tiagopog** [comment]
Cheers!
