### ISSUE TITLE
Is there a way to deactivate the JSON API validation for an action?

### ISSUE THREAD

**Issue by santostiago** [tiagopog/jsonapi-utils#75]
I want all my actions except for `#create` to use JSON API.
The action `create` has too many relationships and becomes cumbersome in the JSON API format. Is there a way to deactivate the validations just for one action?

**Comment by tiagopog** [comment]
Hey there, @santostiago. Sorry for the long delay to answer you, it's been really busy days here.

Yeah, if you really want to avoid conforming that endpoint to JSON:API you can actually skip the method called on the [controller's `before_action`](https://github.com/tiagopog/jsonapi-utils/blob/master/lib/jsonapi/utils.rb#L18):

```ruby
class AppointmentsController < BaseController
  skip_before_action :jsonapi_request_handling, only: :create
  # ...
end
```
